myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include  #  url
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
#    url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from . import views

app_name = 'photo'
urlpatterns = [
     # HTML
     path('', views.HomeView.as_view(), name='home'),
     path('upload/', views.UploadImageView.as_view(), name='upload'),
     path('distort/', views.DistortView.as_view(), name='distort'),
     path('features/', views.FeaturesDetectorView.as_view(), name='features'),
     path('matcher/', views.FeaturesMatcherView.as_view(), name='matcher'),
     path('stitcher/', views.ImageStitcherView.as_view(), name='stitcher'),

     # API TODO USE django-rest
     path('distort/api/<int:pk>', views.Distort.as_view(),
          name='api-distort'),
     path('features/api/<int:pk>', views.FeaturesDetector.as_view(),
          name='api-features'),
     path('matcher/api/<int:pk1>_<int:pk2>', views.FeaturesMatcher.as_view(),
          name='api-matcher'),
     path('stitcher/api/<int:pk1>_<int:pk2>', views.ImageStitcher.as_view(),
          name='api-stitcher'),
]

photo/models.py
from django.db import models
from django.utils import timezone
# from .utils import img_resize, img_distort


def get_path(instance, filename):
    return '{0}/{1}'.format(instance.folder.name, filename)


# Create your models here.
class PhotoFolderModel(models.Model):
    name = models.CharField(verbose_name="Folder name", max_length=120)
    description = models.TextField(verbose_name='Description of the folder')

    def __str__(self):
        return self.name


class PhotoModel(models.Model):
    folder = models.ForeignKey(PhotoFolderModel, on_delete=models.CASCADE)
    img_file = models.ImageField(
        upload_to=get_path,
        verbose_name='Image File'
    )
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        # Resize
        # self.thumbnail = img_resize(self.img_file)
        return super(PhotoModel, self).save(*args, **kwargs)

    def delete(self):
        self.img_file.delete()
        super(PhotoModel, self).delete()

photo/forms.py
"""
Forms module for the photo app
"""

from django import forms
from .models import PhotoModel


class PhotoForm(forms.ModelForm):
    '''
    Simpler form to upload a file.\n
    Fields are 'img_file'
    '''

    class Meta:
        model = PhotoModel
        fields = ['img_file']


# class DistortPhotoForm(forms.ModelForm):
#     '''
#     Simpler form to distort the selected image file.\n
#     Fields are 'img_file', 'f', 'k1', 'k2'
#     '''

#     class Meta:
#         model = DistortPhotoModel
#         fields = ['img_file', 'f', 'k1', 'k2']

photo/views.py
''' Views of the photo app'''

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, TemplateView

from .forms import PhotoForm
from .models import PhotoModel
from .utils.utils import img_distort, img_features, img_features_matcher, img_stitcher


def home(request):
    ''' Return a basic hello world view'''
    return HttpResponse("Hello, world. You're at the polls index.")

class HomeView(TemplateView):
    template_name = 'photo/home.html'

class UploadImageView(View):
    form_class = PhotoForm
    # initial = {'name': 'None', 'img_file': None}
    template_name = 'photo/upload.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()  # handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect(reverse('photo:display'))

        return render(request, self.template_name, {'form': form})


class DistortView(ListView):
    model = PhotoModel
    template_name = 'photo/distort_img.html'


class FeaturesDetectorView(ListView):
    model = PhotoModel
    template_name = 'photo/features_img.html'


class FeaturesMatcherView(ListView):
    model = PhotoModel
    template_name = 'photo/matcher_img.html'


class ImageStitcherView(ListView):
    model = PhotoModel
    template_name = 'photo/stitcher_img.html'


# from django.http import Http404
# from rest_framework.views import APIView
# from rest_framework.response import Response
# from rest_framework import status


class Distort(View):
    def get(self, request, pk, *args, **kwargs):
        img = PhotoModel.objects.get(pk=pk)
        params = [
            request.GET.get('f', None),
            request.GET.get('k1', None),
            request.GET.get('k2', None)
        ]

        img = img_distort(img.img_file, params)
        response = HttpResponse(content_type="image/png")
        img.save(response, "PNG")
        return response


class FeaturesDetector(View):
    def get(self, request, pk, *args, **kwargs):
        img = PhotoModel.objects.get(pk=pk)
        params = [
            request.GET.get('tol', 1),
        ]

        img = img_features(img.img_file, params)
        response = HttpResponse(content_type="image/png")
        img.save(response, "PNG")
        return response


class FeaturesMatcher(View):
    def get(self, request, pk1, pk2, *args, **kwargs):
        img1 = PhotoModel.objects.get(pk=pk1)
        img2 = PhotoModel.objects.get(pk=pk2)
        params = [
            request.GET.get('num', 10),
        ]

        img = img_features_matcher(img1.img_file, img2.img_file, params)
        response = HttpResponse(content_type="image/png")
        img.save(response, "PNG")
        return response


class ImageStitcher(View):
    def get(self, request, pk1, pk2, *args, **kwargs):
        img1 = PhotoModel.objects.get(pk=pk1)
        img2 = PhotoModel.objects.get(pk=pk2)

        img = img_stitcher(img1.img_file, img2.img_file)
        response = HttpResponse(content_type="image/png")
        img.save(response, "PNG")
        return response

# class DistortImage(APIView):
#     """
#     Compute distorted image from selection + parameters
#     and respond with the path to the image
#     """

#     def post(self, request, format=None):
#         data = request.data
#         if data is not None:
#             print(data)
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

photo/templates/photo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Photo App</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="https://kit.fontawesome.com/a0b28ac500.js" crossorigin="anonymous"></script>

</head>


<body>

  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark justify-content-center">
    <a class="navbar-brand" href="#">Project Portfolio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="navbarCollapse">
      <ul class="navbar-nav mx-auto text-center">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'photo:home' %}"> Computer Vision App </a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="{% url 'photo:distort' %}"> Operations Reseacrh </a>
        </li> {% endcomment %}
      </ul>

      <ul class="nav navbar-nav text-center">
        <li class="nav-item">
          <a class="nav-link p-2" href="https://linkedin.com/in/youssefmiftah"> <i class="fab fa-linkedin-in"></i> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link p-2" href="https://github.com/ymiftah"><i class="fab fa-github"></i> </a>
        </li>
      <ul>
    </div>
  </nav>
  

  <div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
      <div class="sidebar-header px-1">
        <button type="button" id="sidebarCollapse" class="btn btn-info">
          <i class="fas fa-bars"></i>
          <span>Toggle Sidebar</span>
        </button>
      </div>

      <ul class="list-unstyled components">
        <li class="active">
          <a href="#cvSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
            <i class="fas fa-images"></i> Computer Vision
          </a>
          <ul class="collapse list-unstyled" id="cvSubmenu">
            <li>
              <a href="{% url 'photo:distort' %}"> Image distortion </a>
            </li>
            <li>
              <a href="{% url 'photo:features' %}"> Image features detection</a>
            </li>
            <li>
              <a href="{% url 'photo:matcher' %}"> Image features matching</a>
            </li>
            <li>
              <a href="{% url 'photo:stitcher' %}"> Image stitching </a>
            </li>
          </ul>
        </li>

        <li>
          <a href="#aiSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
            <i class="fas fa-camera-retro"></i> AI for vision
          </a>
          <ul class="collapse list-unstyled" id="aiSubmenu">
            <li>
                <a href="{% url 'photo:distort' %}"> Image distortion </a>
            </li>
            <li>
                <a href="#"> Image features detection</a>
            </li>
            <li>
                <a href="#"> Image stitching </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">

        <!-- content-->
      <main class="container-fluid m-auto" id="content">
        {% block content %}
        {% endblock %}
      </main>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% block scripts %}{% endblock %}

</html>

photo/templates/photo/display_img.html
{% extends 'photo/base.html' %}
{% load static %}


{% block content %}

 <!-- The grid: four columns -->
  <h1> Select an image </h1>
  <div class="row"  id="scroll-images">
    {% for img in object_list %}
      <img class="im-slide-show m-1" src="{{ img.thumbnail.url }}" alt="{{ img.id }}" onclick="myFunction(this);"></li>
    {% endfor %}
  </div>


    <!-- Range slider image -->
  <h1> Parameters </h1>
  <div class="row maxwidth">
    <div class="col-11">
      <div class="d-flex justify-content-around">
          {% csrf_token %} 
          <label for="f"> f </label>
          <label for="k1"> k1 </label>
          <label for="k2"> k2 </label>
      </div>
      <div class="d-flex justify-content-around">
          {% csrf_token %} 
          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="0" max="1500" step="10" id="f">

          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="-1" max="1" step="0.1" id="k1">

          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="-1" max="1" step="0.1" id="k2">
      </div>
    </div>
    <div class="col-1">
      <div class="align-bottom">
        <button type="button" class="btn btn-primary my-1" id="sendDistort"> Distort </button>
      </div>
    </div>
  </div>


  <h1> Result </h1>
  <!-- Expanded image -->
  <div class="row my-1">
    <div class="col-6">
      <img class="expandedImg" style="width:100%" id="selectedImg">
    </div>
    <div class="col-6">
      <img class="expandedImg" style="width:100%" id="distortedImg">
    </div>
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/scripts.js' %}"> </script>
{% endblock %}

photo/templates/photo/distort_img.html
{% extends 'photo/base.html' %}
{% load static %}


{% block content %}

 <!-- The grid: four columns -->
  <h1> Select an image </h1>
  <div class="row"  id="scroll-images">
    {% for img in object_list %}
      <img class="im-slide-show m-1" src="{{ img.thumbnail.url }}" alt="{{ img.id }}" onclick="myFunction(this);"></li>
    {% endfor %}
  </div>


    <!-- Range slider image -->
  <h1> Parameters </h1>
  <div class="row maxwidth">
    <div class="col-11">
      <div class="d-flex justify-content-around">
          {% csrf_token %} 
          <label for="f"> f </label>
          <label for="k1"> k1 </label>
          <label for="k2"> k2 </label>
      </div>
      <div class="d-flex justify-content-around">
          {% csrf_token %} 
          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="0" max="1500" step="10" id="f">

          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="-1" max="1" step="0.1" id="k1">

          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="-1" max="1" step="0.1" id="k2">
      </div>
    </div>
    <div class="col-1">
      <div class="align-bottom">
        <button type="button" class="btn btn-primary my-1" id="sendDistort"> Distort </button>
      </div>
    </div>
  </div>


  <h1> Result </h1>
  <!-- Expanded image -->
  <div class="row my-1">
    <div class="col-6">
      <img class="expandedImg" style="width:100%" id="selectedImg">
    </div>
    <div class="col-6">
      <img class="expandedImg" style="width:100%" id="distortedImg">
    </div>
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/scripts.js' %}"> </script>
{% endblock %}

photo/templates/photo/features_img.html
{% extends 'photo/base.html' %}
{% load static %}


{% block content %}

 <!-- The grid: four columns -->
  <h1> Select an image </h1>
  <div class="row"  id="scroll-images">
    {% for img in object_list %}
      <img class="im-slide-show" src="{{ img.img_file.url }}" alt="{{ img.id }}" onclick="myFunction(this);"></li>
    {% endfor %}
  </div>


    <!-- Range slider image -->
  <h1> Parameters </h1>
  <div class="row maxwidth">
    <div class="col-11">
      <div class="d-flex justify-content-around">
          <label for="tol"> tolerance </label>
      </div>
      <div class="d-flex justify-content-around">
          <p class="valueSpan"></p>
          <input type="range" class="custom-range px-3" min="0" max="1" step=".05" id="tol">
      </div>
    </div>
    <div class="col-1">
      <div class="align-bottom">
        <button type="button" class="btn btn-primary my-1" id="sendDetectFeatures"> Detect </button>
      </div>
    </div>
  </div>


  <h1> Result </h1>
  <!-- Expanded image -->
  <div class="row my-1">
    {% csrf_token %} 
    <div class="col-6">
      <img class="expandedImg" style="width:100%" id="selectedImg">
    </div>
    <div class="col-6">
      <img class="expandedImg" style="width:100%" id="featuresImg">
    </div>
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/scripts.js' %}"> </script>
{% endblock %}

photo/templates/photo/home.html
{% extends 'photo/base.html' %}
{% load static %}

{% block content %}
<div class="content-text">
  <h1> Welcome </h1>
  <p> Here are some applications of Computer Vision for image processing.</p>
  <p> Most of them are the results of my work following the tutorials from
  the <a href="https://www.cs.cornell.edu/courses/cs5670/2020sp/"> Cornell University course CS5670. </a>
  It is still a work in progress during my free time.</p>

  <p> These tutorials were also a pretext to learn full stack development and make
  this whole website functional and deploy it to Heroku.
  </p>

  <p> The sections on Deep Learning applications are also a work in progress. </p>

</div>
{% endblock %}


{% block scripts %}
<script src="{% static 'js/scripts.js' %}"> </script>
{% endblock %}

photo/templates/photo/matcher_img.html
{% extends 'photo/base.html' %}
{% load static %}


{% block content %}

 <!-- The grid: four columns -->
  <h1> Select an image </h1>
  <div class="row"  id="scroll-images">
    {% for img in object_list %}
      <img class="im-slide-show" src="{{ img.img_file.url }}" alt="{{ img.id }}" onclick="matchSelection(this);"></li>
    {% endfor %}
  </div>


    <!-- Range slider image -->
  <h1> Parameters </h1>
  <div class="row maxwidth">
    <div class="col-11">
        <label for="num"> Maximum number of matches </label>
        <input type="number" min="1" id="num" value="1">

    </div>
    <div class="col-1">
        <button type="button" class="btn btn-primary my-1" id="sendMatcher"> Detect </button>
    </div>
  </div>


  <h1> Result </h1>
  <!-- Expanded image -->
  <div class="row my-1">
    {% csrf_token %} 
    <img class="expandedImg" style="width:90%" id="matcherImg">
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/scripts.js' %}"> </script>
{% endblock %}

photo/templates/photo/stitcher_img.html
{% extends 'photo/base.html' %}
{% load static %}


{% block content %}

 <!-- The grid: four columns -->
  <h1> Select two images </h1>
  <div class="row"  id="scroll-images">
    {% for img in object_list %}
      <img class="im-slide-show" src="{{ img.img_file.url }}" alt="{{ img.id }}" onclick="matchSelection(this);"></li>
    {% endfor %}
  </div>


    <!-- Range slider image -->
  <div>
    <button type="button" class="btn btn-primary my-1" id="sendMatcher"> Match </button>
  </div>


  <h1> Result </h1>
  <!-- Expanded image -->
  <div class="row my-1">
    {% csrf_token %} 
    <img class="expandedImg" id="matcherImg">
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/scripts.js' %}"> </script>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'photo/base.html' %}


{% block content %}

<div class="row mx-auto justify-content-center mt-2">
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %} 
        {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary"> Upload </button>
    </form> 
</div>
{% endblock %}